:source-highlighter: pygments
:pygments-style: monokai
:local-css-style: pastie

Задачи третьей недели
=====================
:Author: Dmitrii Kosarev aka Kakadu
:email:  Dmitrii.Kosarev@protonmail.ch

Упражнения про ввод-вывод
-------------------------
В задачах про утилиты UNIX не надо делать переписывать со всеми фичами исходной программы, достаточно передать суть.

Для облегчения написания, возможно, стоит прочитать про `do`-нотацию.

- Реализовать `hcat`: UNIX утилиту `cat` на Haskell.
+
Без аргументов комндной строки она должна читать строки с `stdin` и сразу печатать их.
+
Аргументы командной строки должны считаться именами файлов и `hcat` печатает содержимое этих файлов.
- То же для утилиты `grep`.
+
Чтобы было совсем круто, надо совпадения выделять цветом.

NOTE: Не все эмуляторы терминала поддерживают цвета!

- Реализовать аналог утилиты `ncal`, которая показывает календарь на данный месяц. Это упраженение скорее на форматирование вывода.
Выделите, пожалуйста, текущий день цветом.
+
https://wiki.haskell.org/Getting_the_current_date
+
  $ ncal
      September 2017
  Su     3 10 17 24
  Mo     4 11 18 25
  Tu     5 12 19 26
  We     6 13 20 27
  Th     7 14 21 28
  Fr  1  8 15 22 29
  Sa  2  9 16 23 30
