:source-highlighter: pygments
:pygments-style: monokai
:local-css-style: pastie
:stylesheet: ./stylesheets/material-teal.css

Задачи неразобранные по темам
=============================
:Author: Dmitrii Kosarev aka Kakadu
:email:  Dmitrii.Kosarev@protonmail.ch

Задачи от М.Симуни
~~~~~~~~~~~~~~~~~~
Составлены М.Симуни (simuni@mail.ru). Вы можете свободно копировать и воспроизводить эти задачи, при условии сохранения ссылки на составителя.

[arabic, start=1]
..  Написать функцию parts2, которая проверяет, можно ли в данном списке выбрать ровно половину элементов, чтобы
  - они строго возрастали
  - в оставшейся половине элементы тоже строго возрастали.
+
В этой задаче элементы не обязательно брать подряд.
+
Примеры вызова: +
- `parts2 [1, 3, 2, 4, 8, 9]`. Ответ должен быть `True` (разбивается, например, на `[1, 3, 4]` и `[2, 8, 9]`)
- `parts2 [2, 3, 4, 6, 1, 8, 9, 7]`. Oтвет должен быть `False`.
+
NOTE: На самом деле, конечно, в Хаскеле есть такая стандартная функция (называется `minimum`), но, пожалуйста, в этой задаче ее не используйте.

.. Опишите функцию `isosc` (от слова `isosceles` - равнобедренный), у которой три параметра - пары целых чисел, и которая возвращает `True`, если соответствующие точки на плоскости задают равнобедренный треугольник, а иначе `False`.
+
Примеры вызова:
+
  - `isosc (0, 2) (2, 0) (2,2)`  должен быть равен True
  - `isosc (-3, 2) (2, 0) (2,2)` должен быть равен False

.. Определить функцию sumprod, которая вычисляет сумму произведений всех пар стоящих рядом элементов.
+
Пример вызова: `sumprod [1,3,2,7]`
+
Ответ должен быть равен 1*3+3*2+2*7 = 23.
+
Дополнительное условие: Задачу надо написать, используя стандартные функции, без рекурсии.
+
..  Описать функцию `height`, которая ищет высоту данного дерева.
+
Примеры вызова:
+
  - `height (Node 1 Empty Empty)` Ответ должен быть 0
  - `height (Node 1 (Node 1 Empty Empty) Empty)` Ответ должен быть 1
+
NOTE: С чего начинать считать, чему равна высота дерева, в котором только одна вершина, у которой нет потомков? Иногда считают, что у такого дерева высота 1, иногда считают, что 0. Давайте для определенности считать, что у такого дерева высота 0.

.. Пусть в нашей программе мы хотим хранить информацию о товарах в кондитерском магазине.
Товары могут быть:
+
  - или тортами, и тогда мы храним их название, и цену (Например, "Санчо" 321)
  - или упаковками конфет, и тогда мы храним их название, цену за килограмм, и вес упаковки в кг. (например, "Белочка" 771 0.25).
+
Опишите тип данных `Candy`, позволяющий хранить такую информацию.
+
Опишите функцию `totalPrice`, которая для данного списка товаров возвращает общую цену всех товаров в списке.
+
Чтобы было хоть какое-то тестирование, пожалуйста, включите в решение пример вызова `totalPrice`, который в результате дает 1000. И назовите его test. Т.е. что-то вроде:
 `test = totalPrice ...какой-то список из товаров разных видов...`
и результат должен быть равен 1000.
+
NOTE: Обратите, пожалуйста внимание, цена для тортов и упаковок конфет вычисляется по разному. Для конфет она зависит еще и от веса.

.. Определите функцию `repeatFunc` с двумя параметрами `f` и `n`, которая возвращает функцию `f.f. ... .f`(т.е. композицию функции с самой собой n раз).
+
Пример вызова: `f = repeatFunc sin 3` должно определить `f x = sin (sin (sin x))`
и после этого можно написать, например, `f 2` и получить `sin (sin (sin 2))` - это примерно 0.7097.
+
// Замечание: Вообще это несложная задача, но, подозреваю, может показаться сложной, просто тема не совсем обычная. Если что то с ней непонятно, или вообще ничего непонятно - можете написать, я постараюсь что-нибудь подсказать.
+
.. Пусть у нас есть лист в клетку. Вертикали и горизонтали в нем перенумерованы. Фигуру из клеток мы задаем, как список из пар целых чисел, например, `[(3,5),(3,6),(4,5),(4,6)]` задает квадрат 2 на 2. Клетки могут задаваться в любом порядке, например `[(3,5),(4,6),(4,5),(3,6)]` описывает тот же квадрат.
+
Описать функцию `getPerimeter`, которая для данной фигуры возвращает ее периметр.
+
Примеры вызова:
+
  -  `getPerimeter [(1,2)]` - должно получиться 4
  -  `getPerimeter [(1,2),(2,3)]` - должно получиться 8
  -  `getPerimeter [(3,5),(4,6),(4,5),(3,6)]` - должно получиться 8

.. Как и в задаче 7-1, мы описываем фигуры на листе в клетку с помощью списка пар целых чисел.
+
Описать функцию `areEqual`, которая проверяет, являются ли две фигуры равными. То есть, можно ли одну получить из другой с помощью сдвигов, поворотов, зеркального отражения, ну и, конечно, изменения порядка элементов в списке.
+
Примеры вызова:
+
- `areEqual [(1,2),(1,3),(1,4)] [(4,0),(3,0),(5,0)]`
- `areEqual [(1,2),(1,3),(1,4),(2,4)] [(2,2),(1,2),(1,3),(1,4)]`
- `areEqual [(1,2),(1,6)] [(10,6),(10,2)]`
- во всех этих вызовах ответ должен быть равен True

.. Описать функцию `multTable`, которая для данного числа n возвращает список списков, представляющий таблицу умножения чисел от 1 до n.
+
Пример вызова: `multTable 4`. Результат должен быть равен:
+
[source,haskell]
----
 [[1,2,3,4],
 [2,4,6,8],
 [3,6,9,12],
 [4,8,12,16]]
----

.. Опишите две функции, `countEven` и `countEven1`, которые для данного списка вычисляют количество четных чисел в этом списке. (Т.е. надо написать две версии одной функции).
+
Дополнительные условия:
+
  - В функции `countEven` можно использовать _только_ стандартную функцию foldr. Точнее, можно, конечно, использовать функцию `mod`, но нельзя использовать `map`, `filter` и т.д. Можно (но особо не нужно) задавать свои нерекурсивные функции. Можно, конечно, использовать лямбда-выражения.
  - В функции `countEven1` можно использовать любые стандартные функции, кроме `foldr` и `foldl` (в частности `map` и `filter`), и тоже, если надо, можно использовать свои нерекурсивные функции и лямбда-выражения. Но _нельзя_ определять свои рекурсивные функции.
+
Примеры вызова:
  - countEven [4, 3, 14, 8, 5, 33, 6]
  - countEven1 [4, 3, 14, 8, 5, 33, 6]
  Ответ должен быть равен 4

.. Опишите функцию myfoldl, которая делает точно то же, что и стандартная функция foldl (т.е. сворачивает все элементы слева направо).
+
Пример вызова: `myfoldl (+) 0 [1,2,3]`
+
Функция должна вычислить ((0+1)+2)+3, причем вычисления должны происходить именно в таком порядке.
+
Замечания:
+
  - нельзя, конечно, использовать стандартный `foldl`
  - можно посмотреть определение `foldl` и переписать, но, конечно, я бы советовал попробовать придумать самостоятельно, это интереснее.

.. Определите функцию repeatFunc с двумя параметрами `f` и `n`, которая возвращает функцию f.f. ... .f (т.е. композицию функции с самой собой n раз).
+
Пример вызова: `f = repeatFunc sin 3` должно определить `f x = sin (sin (sin x))`
и после этого можно написать, например, f 2 и получить sin (sin (sin 2))- это примерно 0.7097.
+
Дополнительные условия:
+
  - задачу надо написать, используя стандартные функции, без рекурсии.
  - можно определять свои функции, но они должны быть не рекурсивными

.. Пусть мы представляем матрицы, как списки списков. Например, список xss = [[1,2,3],[4,5,6],[7,8,9]] описывает матрицу 3 на 3, у который первая строка состоит из чисел 1 2 3 и т.д.
+
Описать функцию diagonalSums, которая возвращает список из сумм элементов на всех диагоналях матрицы, параллельных главной диагонали.
Например, для описанного выше списка xss ответ должен состоять из чисел 7, 4+8, 1+5+9, 2+6, 3
+
Замечания:
+
  - Суммы в ответе должны идти именно в таком порядке - начиная с диагонали из одного элемента в левом нижнем углу, и заканчивая диагональю из одного элемента в правом верхнем углу.
  - Можно считать, что мы точно знаем, что данные описывают квадратную матрицу. То есть, количество чисел в каждой строке равно количеству строк. Это можно не проверять.
+
Пример вызова: `diagonalSums [[1,2,3],[4,5,6],[7,8,9]]` Должно получиться `[7,12,15,8,3]`

.. Описать функцию dioph, параметры которой - два списка из 4 целых чисел `[a, b, c, d]` и `[k, l, m, n]`, и которая возвращает список из 3 целых чисел [x, y, z] таких, что:
a*x+b*y+c*z=d
k*x+l*y+m*z=n
+
Замечания:
+
  - Что делать, если таких чисел нет - на ваше усмотрение. Можно выдать ошибку, можно вернуть (0, 0, 0) и т.д. В тестах таких случаев не будет.
  - Числа в тестах могут быть достаточно большими для того, чтобы эту задачу не было смысла решать простым перебором, надо придумать что-то более эффективное.
  - Эта задача более-менее сложная. Решение, которое я (Симуни) знаю - довольно громоздкое, в нем надо рассматривать разные вырожденные случаи и т.д.. Т.е. это для тех, кому интересно решить что-то немного посложнее.
+
NOTE:  Понятия не имею как это решать :) Косарев

.. "Крестик"
Описать функцию cross, которая для данного числа n возвращает список списков, представляющий матрицу, в которой на главной и побочной диагоналях стоят 1, а все остальные элементы равны 0.
+
asdfasd
+
  - Для `cross 4` pезультат должен быть равен:
[source,haskell]
----
[[1,0,0,1],
[0,1,1,0],
[0,1,1,0],
[1,0,0,1]]
----
  - `cross 5` Результат должен быть равен:
[source,haskell]
----
[[1,0,0,0,1],
[0,1,0,1,0],
[0,0,1,0,0],
[0,1,0,1,0],
[1,0,0,0,1]]
----

.. Перечислить все способы выдать данную сумму n монетами по 2, 3 и 5 коп. Результат должен быть списком списков целых чисел, каждый внутренний список - это список из трех элементов [k,l,m], где k - двухкопеечных монет, l - количество трехкопеечных, m - количество пятикопеечных монет.
+
Пример вызова: `coins 10`
+
Должно получиться: `[[5,0,0],[2,2,0],[0,0,2],[1,1,1]]` (порядок троек в ответе может быть и другим).
+
Замечания:
+
  - Вообще это упражнение на list comprehension. Но, если хотите, вы можете решить задачу и без list comprehension, как хотите.
  - Большинство людей эту задачу пишут не совсем эффективно, точнее, не замечают возможность немного изменить программу, чтобы она стала гораздо эффективнее.

.. Опишите функцию foldTree, которая для дерева делает что-то аналогичное foldr или foldl для списков. Она должна вызываться так:
+
`foldTree (+) 0 t` — ищет сумму всех элементов в дереве
+
`foldTree (*) 1 t` — ищет произведение всех элементов в дереве

.. Можно ли в предыдущей задаче придумать что-то более общее? Например, придумать такой вариант foldTree, который позволяет реализовывать более сложные функции (например, искать высоту дерева и т.д.). Если придумаете, предложите какой-нибудь такой вариант.
+
Замечания: Условие, естественно, не совсем строгое (но так и в жизни часто бывает..).

.. Пусть мы хотим описывать в программе на Хаскеле электрические схемы. Мы считаем, что электрическая схема - это:
  - или сопротивление, тогда известно его величина в омах
  - или две схемы, соединенных параллельно - или две схемы, соединенных последовательно (На самом деле есть схемы, которые таким способом не описать, ну и ладно..)
+
Опишите
  - тип (data) Scheme, который позволяет описывать такие схемы.
  - функцию totalResistance, у которой один параметр - схема, и которая возвращает значение общего сопротивления для этой схемы. Например, для двух сопротивлений 4 Ом, соединенных последовательно, функция должна возвращать 8, а для двух сопротивлений 4 Ом, соединенных параллельно, функция должна возвращать 2.


.. Описать функцию `zipWithTree`, которая соединяет, так же, как zip, дерево и список. В результате должно получиться дерево пар. Если в дереве больше элементов, чем в списке, то лишние надо удалить из дерева.
+
Примеры вызова:
+
  - `zipWithTree (Node 35 (Node 12 Empty Empty) (Node 70 Empty Empty)) [1,2,3]`
    Результат должен быть равен `Node (35,1) (Node (12,2) Empty Empty) (Node (70,3) Empty Empty)`
  - `zipWithTree (Node 35 (Node 12 Empty Empty) (Node 70 Empty Empty)) [1,2]`
    Результат должен быть равен `Node (35,1) (Node (12,2) Empty Empty) Empty`
