:source-highlighter: pygments
:pygments-style: monokai
:local-css-style: pastie
:stylesheet: ./stylesheets/material-teal.css

Задачи к третьей неделе
=======================
:Author: Dmitrii Kosarev aka Kakadu
:email:  Dmitrii.Kosarev@protonmail.ch

Про типы данных
---------------

=== Про Continuation-passing style

. Реализуйте foldr через foldl и примитивы λ-исчисления (т.е. не используя других функций). Всё очень просто, если предположить, что передаваемая функция коммутативна.

. Аналогично предыдущему, fold через foldr.

. Спроектируйте `fold` для списков так, чтобы при вычислении можно было прерваться. Например, мы перемножаем спиок чисел; встретив 0 нужно остановиться и выдать ответ.

. Опишите ADT для арифметики: там должны быть константы-числа, переменные и бинарные операции сложения и вычитания. Реализуйте функцию `eval`, которая принимает начальные значения некоторых переменных и вычисляет выражение в число. Функция `eval` не должна сильно расходовать стек.

. Для предыдущего типа данные реализуйте функцию `simplify`, которая будет упрощать выражение, пока оно упрощается. Виды упрощений: операции над константами, умножение на ноль, вычитание из самого себя, common subexpression elimination, etc.
