:source-highlighter: pygments
:pygments-style: monokai
:local-css-style: pastie

Функциональное Программирование (матмех, осень 2017)
====================================================
:Author: Dmitrii Kosarev aka Kakadu
:email:  Dmitrii.Kosarev@protonmail.ch

// [role="col-md-4"]
// ====
// [panel,primary]
// .{toc-title}
// --
// * xref:about[Пролог]
// * xref:week1[Первая неделя]
// * xref:week2[Вторая неделя]
// --
// ====

[[about]]
Пролог
-----

http://ocsigen.org/js_of_ocaml/2.8.4/files/toplevel/index.html[OCaml прямо в браузере]. Может для Haskell'я тоже такое есть...

GHC и WinHugs и как ими пользоваться:

* Самая распостраненый способ уставновить Haskell - это Haskell Platform (http://www.haskell.org/platform).
  Работает для Windows, Linux и Mac. Для курса будет достаточно минимального варианта установки.
* В Haskell Platform есть простые среды разработки GHCi и WinGHCi. http://msimuni.wdfiles.com/local--files/fp4/StartingWithGHC.pdf[Вот] краткая инструкция о том, как начать с ними работать.

Книги
~~~~~
http://learnyouahaskell.com/[Learn You a Haskell for Great Good]

https://vk.com/wall-54530371_9051[Денис Шевченко "О Haskell по-человечески" 2014] Мало страниц, большой шрифт, хорошо рассказанные азы
на простых примерах

https://anton-k.github.io/ru-haskell-book/files/ru-haskell-book.pdf[По-русски], свиду нормально написано, но проект книги заброшен и
код местами устарел и не компилится.

Можно также найти Р.Душкина "ФП на языке Haskell". https://wiki.haskell.org/Books[Ещё список на Haskell Wiki] (в том числе и на русском).

А также некоторые задачи поможет решить "Purely Functional Data Structures" от Chris Okasaki (есть русское издание).

Ссылки
~~~~~~
https://vimeo.com/153042584[Yaron Minsky - Why OCaml]. Хорошо для общего развития: какие языки бывают, что от хорошего языка программирования требуется, и т.д.

http://queue.acm.org/detail.cfm?id=2038036[OCaml for the Masses] Большинстов аргументов переносимо и на Haskell.

https://two-wrongs.com/a-gentle-introduction-to-monad-transformers[Адекватный туториал] про трансформеры

https://ruhaskell.org/links.html

Курсы на степике "какие есть": https://stepik.org/course/75/ и https://stepik.org/course/693/ от Д.Москвина

[[week1]]
Неделя 1
--------
Введение. Рекурсивные функции над числами

link:exercises1.html[Упражнения 1]

Если официальные упражения сделаны, можете поискать интересного среди link:exercises_all.html[упражнений, неотсортированных по темам]. И ещё тут планируются упраженеия посортированные, но официально необъявленные.

[[week2]]
Неделя 2 (11 сентября)
----------------------

link:exercises2.html[Упражнения 2 (Списки и прочее)]

link:exercises3.html[Упражнения 3 (Про IO)]

[[week3]]
Неделя 3 (18 сентября)
----------------------
link:exercises4.html[Упражнения 4 (Про (алгебраические) типы данных)]

Умная http://chris-taylor.github.io/blog/2013/02/10/the-algebra-of-algebraic-data-types[ссылка] про алгебру в алгебраических типах данных (Algebraic Data Types)


[[week4]]
Неделя 4 (25 сентября)
----------------------

Упражнений на эту неделю я обещал не задавать. Если кто-то всё зарешал, то выкладывайте на гитхаб решения, я попробую к чему-нибудь придраться.

[[week5]]
Неделя 5 (2 октября)
--------------------

link:exercises6.html[Упражнения про исчисление высказываний и немного про списки]

Что-то Вы забуксовали с решением домашних задач, не успев дойти до интересной темы (типы данных). Соберитесь (◑‿◐), свалить всё на сессию нельзя ещё 2 месяца.

Тем временем у меня есть несколько замечаний как писать нормальные функции на Haskell.

  - Если Вам хочется использовать функции `head` и `tail` -- попробуйте переписать через pattern matching. В стандартной библиотеке эти функции могут кидать исключения, в то время как pattern matching должен отчасти решать эту проблему.
  - В Haskell нет сокращенного `if` потому, что его функцию может выполнять обычный `if`. Конструкция `cond ? a : b` появилась в языке
  С только потому что там присутствует разделение понятий expression(выражение) и statement(утверждение). Statement'ы нельзя писать внутри выражений.
  - Если вам хочется использовать `if`, то стоит попробовать переписать свой код используя фишку pattern-matching, которая называется guards. https://en.wikibooks.org/wiki/Haskell/Control_structures#if_and_guards_revisited[Умная ссылка].
  - Для ваших алгебраических типов (а также для встроенных в язык списков) Наskell умеет указывать на неразобранные при pattern-matching случаи. Так что рекомендую запускать REPL с помощью команды `ghci -fwarn-incomplete-patterns -Werror`

[[weeklast]]
Задачи "на потом"
-----------------

Если официальные упражения сделаны, можете поискать интересного среди link:exercises_all.html[упражнений, неотсортированных по темам]. И ещё тут планируются упраженеия посортированные, но официально необъявленные.

link:exercises5cps.html[Упражнения 4 (Про Continuation-passing style)]

////
[glossary]
Example Glossary
----------------
Glossaries are optional. Glossaries entries are an example of a style
of AsciiDoc labeled lists.

[glossary]
A glossary term::
  The corresponding (indented) definition.

A second glossary term::
  The corresponding (indented) definition.
////

ifdef::backend-docbook[]
[index]
Example Index
-------------
////////////////////////////////////////////////////////////////
The index is normally left completely empty, it's contents being
generated automatically by the DocBook toolchain.
////////////////////////////////////////////////////////////////
endif::backend-docbook[]
