:source-highlighter: pygments
:pygments-style: monokai
:local-css-style: pastie
:toc:

Функциональное Программирование (матмех, осень 2019). Домашки
=============================================================
:Author: Dmitrii Kosarev a.k.a. Kakadu
:email:  Dmitrii.Kosarev@protonmail.ch


== Задачки для Скалолазов

Дополнительные, так как у них слишком короткий курс на Степике.

=== Алгоритм DPLL

Задача из мира математической логики про выполнимость формулы языка высказываний. В том году давал на экзамен. Сейчас хочу сам алгоритм  с какими-нибудь оптимизациями (например, hash consing).

Сам алгоритм должен довольно легко гуглиться.

=== Окологеймерская

Запустить моделирование мира, где персонажи что-то делают и куда-то стремятся.

NOTE: Детали обсуждаемы потом

=== Задача про верификацию и триплеты Хоара

Фиксировано AST языка программирования с числами, условиями, присваиваниями и циклами. Программы аннотированы триплетами Хоара. Проверить, что аннотированы корректно.

Про триплеты Хоара по-русски можно читать, например, в книжке Герасимова "Математическая логика".



[[general_tasks]]
== Остальное

Дальше идет N тем, которые будут определять задачи вида

* Напишите тип данных для представления программ на мини-языке.
* Сделайте парсер этого языка (как именно делать   будет сказано в курсе Москвина и немного на лекции)
* Сделайте интерпретатор языка (по аналогии с тем как мы писали `eval` для арифметических выражений на паре №2)
* Реализуйте какое-нибудь преобразование программ.

[[two]]
=== 0 фывафывафывафы

[[three]]
=== 1 NOTE: написать подробнее


=== 2


=== 3




ifdef::backend-docbook[]
[index]
Example Index
-------------
////////////////////////////////////////////////////////////////
The index is normally left completely empty, it's contents being
generated automatically by the DocBook toolchain.
////////////////////////////////////////////////////////////////
endif::backend-docbook[]
